package com.justin.eagle.bank.matcher;

import org.skyscreamer.jsonassert.ValueMatcher;

public class TimestampValueMatcher implements ValueMatcher<Object> {

    /**
     * The timestamp generated by the open api spec uses Instant object and when serialzed to string we we get upto nano seconds prcision
     * This might show discrepencies when comparing the results.
     * So this function will check till the millisecond precision
     * @param o1 the first object to check
     * @param o2 the object to check the first against
     * @return
     */

    @Override
    public boolean equal(Object o1, Object o2) {

        var value1 = o1.toString().substring(0, 23);
        var value2 = o2.toString().substring(0, 23);
        System.out.println(value1);
        System.out.println(value2);

        return value2.equals(value1);
    }
}
